var entries = [
    {latlng: [37.840455, -122.257520],
     date: 'December 30, 2018',
     title: 'This was our Oakland',
     location: 'Oakland, CA, USA',
     url: 'https://www.schemebasedadventure.com/2018/12/30/this-was-our-oakland/',
     corner1: [37.847080, -122.310148],
     corner2: [37.791333, -122.212991],
     line: '' },
    {latlng: [37.742698, -122.432150],
     date: 'January 18, 2019',
     title: 'Tomorrow to fresh woods, and pastures new',
     location: 'San Francisco, CA, USA',
     url: 'https://www.schemebasedadventure.com/2019/01/17/tomorrow-to-fresh-woods-and-pastures-new/',
     corner1: [37.710129, -122.507835],
     corner2: [37.807414, -122.385118],
     line: "ku}eFpkeiVyJoHeAhCU`AOx@M`AAl@@VXhAb@`Bz@pCj@tBDHRJh@xB|@fEf@lBb@jAr@zAdAjBx@lA~AbBjA~@tBfAtD`A`BVbFl@zDb@~JjA`C\\ZVLFrEr@bFv@bBZhAP~Dl@~B^r@JHHPFp@LRDnB`@f@Pp@`@n@l@b@p@JRZz@TnAHxAExAq@nFWfBaB`NaAtHAX@RDV_@`Cm@~D]dC_BrKMdAK`BElC@|ANzB`@hDr@zEp@nEHNDJN~@LnAFbBCbCSjCe@xBw@|BgAdCw@tBUx@UhAQhBEfABhBHdAV~Aj@lBdAfD`@fBV|AbBbM\\jC@RI|@VjA`A|G~AjM^dFD^FhAl@jO@bB@lDEtEE~BNlEZhDP|AJr@`@zCj@zEx@bFJ~@f@vBn@tCd@xAf@hBd@dCj@`E\\vDZhGTlHl@jQn@`N`AvNrJrnAhBrU`@zD\\bC^tBd@vBf@lBx@hCnAbDdOb[`BfD~AhDz@vAlAbBhArAj@h@rElDnAbAfAdAlBpBzCjDdCrC|B~Bl@bA^^bDnDvB`CdIrJzJtKlK`LxU~VjDzDrDvDnIrJhGxGtI`JtD~D~DjE^\\vApAhApAdBlBlC`DlBbCx@pA\\h@h@hAJXJT`@t@lCtFrAxBp@bAPThH|JxFjIpP~UpAlBlApBzBbE~BtEdAhBv@fAj@j@LH`@XlAn@|Ah@|ATtAD`BE`BSr@Mh@MpBw@rAk@|@[\\Qn@QfB[f@GrAGdKe@zAGv@A|AGdH]x@@fAD~@LhAZ~@XtAr@bAj@pAj@r@Vp@Rv@HdADnAGxAYrAi@hAy@v@y@dBeC`AyAp@y@t@s@fAq@hAa@v@OrAM`GWdHYr@AzA@x@FLRDDNDtD`AjAZDFd@PlA\\b@Rh@f@Zl@Ph@LPj@zFXnBjAjFJt@BjA@rEHbMJfRJ|SRdVDlB@TXEzH]|DQ`@?XBlCr@bG~Al@dUVzLd@rS" },
    {latlng: [37.617948, -122.391691],
     date: 'January 23, 2019',
     title: 'We made it! (?)',
     location: 'SFO, San Francisco, CA, USA',
     url: 'https://www.schemebasedadventure.com/2019/01/23/we-made-it/',
     corner1: [37.604199, -122.410133],
     corner2: [37.633354, -122.356803],
     line: "crjeFzogjVKwE`DO?O`EOlAGBRNYBW`GgMDKLKJEb@IJ@l@UN?`Bb@LDBDFGnEsE`@i@JWFWXs@ZYH[VmGDaAv@P`@JPHRNDYVi@f@w@h@c@\\IB@F@Lv@Vr@Zd@r@j@^N^D`BHj@H?B?F@DHDHG@A^RTFPANCVQRMBZJh@Xz@V`@f@ZZFZBd@BFcB?aCEiEGcCOcDSqCa@uDKe@MyAIuBA{ABqAEa@?IAQDcGA{@IaBEs@EOOUQuBc@wCWmAOg@Ao@CSYaA{AiF{EcP]cBM{AEgA@{@H}ALcA\\aBj@{A^u@z@gAlAeAtBgAzBeATUfAe@v@YfA[fCi@tE_AhHiBn@@h@S`@MlIcCbGeBnEuAfCw@~Cy@bFkAzNgCbE}@nA_@hAc@rAo@|ByAdHuFn@a@xAu@bBs@x@WtBe@|B]`TuCpJkArDi@~WsD|eA_Opj@yHzNyBlBSrAGtCAfAD`BJnAPfARnBf@zBr@xBx@nBx@xBbAbEzBdC|AvDpCzBhBvBpBpP|O|ErEjBrBhB`ChA~AfAfBp@jAnMnUx@nAfApAz@~@dA~@|B|AtAt@dEdBnDzA|CjAdCp@zAVlCX~AFhB@|GWtGW`CK`a@{AfPs@~BSbCYfBa@~Cy@dCy@lBw@pASdCs@xBo@`ASd@GXMFAPEvGk@x@G`Da@hJ}@tNeAhFg@zB]dB[zDkAxEyAfHsBjKgCjI}AdB_@dD{@R@PAnHuB|GoBh@Sb@Wr@o@\\e@`@w@Ng@TkAFe@AS?}@GqAUoCYoC_@_Bu@{CgAqFMo@YoCCg@B[N[RMXIt@Qn@hEpAfIc@?g@@}GnBQJMNGHY]uB{M" },
    {latlng: [10.425416, -75.546079],
     date: 'January 25, 2019',
     title: 'Old City, New BRT: Notes on Transcaribe',
     location: 'Cartagena, Bol&iacute;var, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/01/25/old-city-new-brt-notes-on-transcaribe/',
     corner1: [10.433460, -75.554840],
     corner2: [10.392480, -75.470035],
     line: '' },
    {latlng: [10.423455, -75.544804],
     date: 'January 28, 2019',
     title: 'Cartagena de Indias',
     location: 'Cartagena, Bol&iacute;var, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/01/28/cartagena-de-indias/',
     corner1: [10.412783, -75.528361],
     corner2: [10.431804, -75.555225],
     line: "ehs~@`ablMMDY@VtBXrBu@Pu@Na@}Bs@_FS_BG?s@EO@sCp@EOUe@FAd@GzDsAl@QHAb@Jp@ZNBP?zAe@tF_B`@KrB[RbB\\vA" },
    {latlng: [11.268952, -73.838061],
     date: 'February 1, 2019',
     title: 'Glimpses of Coste&ntilde;o Beach',
     location: 'Guachaca, Magdalena, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/01/glimpses-of-costeno-beach/',
     corner1: [11.340159, -74.270697],
     corner2: [10.368081, -73.220783],
     line: "yxr~@vyalMsBlD}AwF~CqBdEgK`GiHkHvIo@tHsTtC{RYcUkV{IkR}JoJoVuj@a\\a]kgA{vAum@er@op@ay@o{Ay_AsyCweAk|Acg@wtBma@{g@cJ_~@iYkr@sFce@yGy_B_KoaA}SmMIaOrN_k@d_@_XeDgR_TqM{f@i_@swAik@kcAmSw}@uYoZcz@me@qReq@lL_r@yPufA_Kcq@JidAcG{]_LqKqm@}a@sZob@aGwk@__AygBwkAiyBse@_o@{j@i\\giBwt@sb@gSaa@gRcJ}PwMwWcpAqm@q_AiqAuVk_BkMk|@iNw]a\\_l@oOoXuSwQ}hA{XyScPu`@as@}YkVezAmiAuRy{@wJqWwOcG_bAc]mK}YoNmYwm@mT{X}f@{@q`A_b@ssAwv@gjAm^yaAmg@{g@}WinAmNqbAei@ik@kZc\\kSaImg@qLoWa\\op@kKso@nR}QJac@wYiFo`AgOuUgRuJ}l@^mc@sUod@oj@dCevAdDo}A}Dwz@qRae@mo@{Ukg@kFig@fEaWkCuMqL_MagAwj@woAuNkYeH_i@yQiyCsTkmDnE_\\xW}i@jLoC`b@vFlWoGddB_^xr@Nb{@bMneAeOhr@qMzd@nAzk@f@pWaQnb@_iAbHu`@iCqmAiFyy@k]_j@cPgPuq@eXsu@iVgAeJoBgR}JuRrCeO^ebA_Ny_@{ZcQkm@mh@q^_Tul@}X{_@}g@ws@}jCcw@i~@yf@gx@rGulAcF__BuVwj@eOc{@yGim@xEirAbCyc@|Suh@hq@_q@zC_g@tKs]|Mcy@fe@ceDgKur@fk@}bC`eA{pK|JogA{F}l@mCm~AnFcyAcA_rBfO{zAcj@yxEcMkoB{MoaAg^chAoXqnAga@au@ik@ilA{Tca@D_u@bIaiB|CggBcsAuZmq@qj@{]}J_fA}GktAzOguAzc@soAnLiPmAsb@pBgwA_AmxEgCkgA_Re{AsKak@yO_c@mn@sN}Nyh@w@ca@gNgJoOsR}c@ys@}t@}Ng`@{Yga@qm@m\\sMoBoUyv@cc@sr@cHg_@wY{h@_{@}qAs`@cs@s_@ad@mZaRoMkW{TuVZwItCqWrGeKeIaMSkPrG{HpCwJ}NwSr@qVqLkf@cNkGwD_SnLeR}KoMqMad@mFydA_a@cdCyIgj@Lq^a@arAdL{gBlTqj@_Iw_A|U_h@yAsa@uHqa@hCqW|GmoAcUi\\_Emd@cNww@eYgVsQuXjlAyjC`Ywf@zXoBfJsMdJkSY{NqWq@wJaBO_c@bGg^tN{`@" },
    {latlng: [4.596126, -74.072129],
     date: 'February 5, 2019',
     title: 'Sh*t happens, or: Bogot&aacute; Part 1',
     location: 'La Candelaria, Bogot&aacute;, Distrito Capital, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/05/sht-happens-or-bogota-part-1/',
     corner1: [4.618136, -74.086144],
     corner2: [4.593483, -74.064933],
     line: '' },
    {latlng: [4.623853, -74.065855],
     date: 'February 6, 2019',
     title: 'An Entire Blog Post Dedicated to Just One Urban Park!',
     location: 'Santa Fe, Bogot&aacute;, Distrito Capital, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/06/an-entire-blog-post-dedicated-to-just-one-urban-park/',
     corner1: [4.626781, -74.066826],
     corner2: [4.619964, -74.056696],
     line: "cu`[pebcM}DlHmDkBdBeD|@cBv@yAkAo@gGeDaEyBoA}@wB_Ag@UIUa@u@w@iAm@u@y@k@iBy@KIIDONe@p@YTa@NQLE?I@a@W_@Mo@M}DcBqEoBkAa@qCc@u@KWGWMi@YWAs@@e@B{@N]JWN]X_@n@QPsAfCw@dBi@rAu@rAm@x@iAjAYXQDMDcAf@WNYGiFe@}F]}Be@qA[qA]oBc@cAKq@Y]EeASmFy@iBSs@SmFiBsCeAc@K{DgAwCo@gDi@" },
    {latlng: [4.661467, -74.060913],
     date: 'February 10, 2019',
     title: 'Ten things we learned in Bogot&aacute;',
     location: 'Chapinero, Bogot&aacute;, Distrito Capital, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/10/ten-things-we-learned-in-bogota/',
     corner1: [4.700212, -74.026903],
     corner2: [4.594948, -74.086740],
     line: "sbf[x`acMuIsAsDk@}OgCsBc@}EmAwA]cEs@m@ImBEmHKmCEcDUyAQ}Fw@{HoAgIwA}UiEmAWYKsB`EcBzDmAhDq@zCKh@aCWmC[uEc@qLqA}Ek@m@I_Bm@oBu@_CiAkD}AoA[gKkAyLaAyHu@l@}@PY" },
    {latlng: [4.641356, -75.577945],
     date: 'February 14, 2019',
     title: 'Home in Salento',
     location: 'Salento, Quindio, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/14/home-in-salento/',
     corner1: [4.630317, -75.580945],
     corner2: [4.644788, -75.563751],
     line: '' },
    {latlng: [4.638197, -75.486454],
     date: 'February 15, 2019',
     title: 'Valle de Cocora: "hard on the thighs, easy on the eyes"',
     location: 'Valle de Cocora, Quindio, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/15/valle-de-cocora-hard-on-the-thighs-easy-on-the-eyes/',
     corner1: [4.622995, -75.450015],
     corner2: [4.646162, -75.492585],
     line: "wvi[rmhlMMMQGeAB[CMSIe@Em@F]H{@HYVUxB{@`@YLMFQAOIQKIe@OMMEG?KNg@Fc@CQEIMIQCG?aA\\UFOCECk@aAaAgAGU?OBGXMRIxAIn@IfATL?RCHMBw@P]Z[p@c@HS@QAMg@o@IQCa@@g@EOMUy@[IAUBOLGLAn@GZMHa@JW?QE[]y@e@OMAW@IJI\\Ib@@^G\\Sv@kATShAo@lBc@z@Gv@FT@dAj@`@Xv@L`Ac@mA}BgA}BmA{Bi@kAEaAAaACc@GM_@a@_@OK?cBVa@Da@Ei@SOOAQHMf@]z@k@rAsA^]Pg@Fc@Ga@U[m@i@KSGS?]H[NQTIh@M^QZ[No@@_@HSJQNIZYDM?SIUuA{BEa@BOXWXa@Hg@RUp@e@L[@QCUMs@[kB?Q@mALcBKm@Ik@q@aCoAqDO}@My@?a@?[d@qBd@sAz@uC\\iB@gA?iFLwDPyG?{CHm@h@wBJo@?]Ey@OqA?{@@_@XmA|@mDh@w@d@k@Zg@N}@\\cCF]Tc@`@u@Nm@DeACu@Am@IUo@}@k@i@SIc@Ia@?U?_@GYSUg@a@aBSc@e@s@}@kAS{@Gs@@_@LkA\\mCL]~@mAb@u@^{@bA}F\\yBT}E@{BEYS{@Oi@AS?UFMnC_Dt@qBj@qADo@Mg@Wy@]iBGs@Do@Nw@A]OYa@a@Qg@A]J]P_A@c@Yo@GW?YDYNyADeB@Od@oA@g@[gAJ}ARaBI{A@Kn@eASmDbAyCJkBDcC]qAg@yABk@r@sBn@{BnAoDzCyHZoDpBeBt@uA?uA@EvByC?oCMsB?{@v@qCh@kA`As@v@kBf@gF?Mc@q@o@s@Ba@TyAbAqC\\uACkAOsGw@aCQyC`@kP@OfAsAn@[HEjBiGDmAYyCS_AsA}@}Ai@{@e@{@iAu@}AEKHgADEn@?pAh@r@x@NNr@Hd@ITa@GsBqNwZmCoGkH{NAe@" },
    {latlng: [6.216474, -75.587888],
     date: 'February 17, 2019',
     title: 'Multimodal Medell&iacute;n',
     location: 'Medell&iacute;n, Antioquia, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/17/multimodal-medellin/',
     corner1: [6.200864, -75.609165],
     corner2: [6.306383, -75.497809],
     line: "u{h[hmvkMt]zaAuI~tAsYzkBqJvpAnJjX}In`A_Adz@gHhPbJ~IkA|HmMhF`GEyBvR|Ibg@wJzL`JpRxMtIqNj@eWq@w`@b@mZ|XjGrLuGrSyKzELiF{LqTo`@d@iaA~YkgAff@y^xAqBqQmh@pLeOqL}G~NyS|@sFiPuOjT|Hl^eNlH}XfH{B|c@mq@hh@e^jv@qi@`p@aK~{@uf@b~@g\\tDy`A~jBgs@dp@i}@vR{Wp]}JgBn@sMyQcAyE{B{i@~EefA{MoW{D\\{M{gAu`@u_AyYyhAkt@{t@kdA_HoWq]kWvE_q@lVbTlAoKOub@PfH_F_`@coAoWcy@vEqn@cb@oeA{DwcAoHq^jEqw@oCgdBiYibBeVqx@mCybAfLsdA{D{iAgi@wG_}@rGaPmPcIkbBcZiZQoItTqt@rIk|@oBaSvDwYgOwYj^sfAh~@eI|j@oa@pLcJ`o@rL`v@ma@`r@cjAdf@ib@aIiW|L}v@Hs^rGiAnc@m_@`l@yy@vOunBbVmh@sLanA_dAe\\cN}QjJwZ_Cw]^k^yRa[q_@yj@uOyToj@ur@sE{`A~Kub@wRuD|U{k@hQk[b]}h@LsbBzq@}|@rAoa@j]~VjByd@xUky@_XqeAgh@{z@a[qFmf@|Eom@gr@mPew@lHum@X_u@e_@qDod@w[mVga@gXalCud@qWuEy\\ib@qvA_k@uyBuV}~Aga@a}AsXkg@yOml@_DogCaQmWiPs\\jJaqA`Oqz@jBm_@ye@_PoYik@iFg{A|Iyf@|^_hDOctAtSmfCbXu}AnR_X[kT|_@mh@oG{s@Tos@_n@q^gw@e[aEgSbS_RrjAc`@heAet@ScrBaEid@aMaUzRiZdDcq@dAma@q@}m@rb@io@Dac@xU_\\gK{RuV_^iA{p@lGo~@uEytAuSw]cHvDwZdA{L}Pl@oMyFwi@kEkb@}ByRlE_PuI{\\dFyZ_Hh@yc@yOzEyQcPdDcP_OaOuQvPqg@o_@`FsVu]_Eap@aEjDkXbXw[tM}GyIoSoo@b[wJoCeEtNwYtVcVtDoNvP{[~Qwd@_@_t@tBuLpKuw@fC{cA`W_`AbGsl@bZerAb@em@fKql@j\\_k@re@}g@dUc^xW{FxIT~Qci@pK}j@`PmqAbLqd@fRmw@zGm_@hT}pAxa@soA@kn@vUud@mA}bAwQeuAzOsTtHyS_Fuw@H?{SmYwFoqAzIau@fHwt@N{VyEii@gjBoYsw@m|@{d@eaAc~@wcAql@wjBuUo\\}BpOaD_Ev[}Pv_@hH~Q}AyG" },
    {latlng: [6.244136, -75.584366],
     date: 'February 20, 2019',
     title: 'How We Did It (or: The World Is a Smaller Place Now)',
     location: 'Medell&iacute;n, Antioquia, Colombia',
     url: 'https://www.schemebasedadventure.com/2019/02/20/how-we-did-it-or-the-world-is-a-smaller-place-now/',
     corner1: [6.238715, -75.600106],
     corner2: [6.250379, -75.578060],
     line: "}c}d@hgjlMwBUOBMNIh@GfAFPJDf@FpAHLFFHDL?NALILQLSDgBu@_@SOOK[CU?QBU\\iCJiAB}AZq@VEf@OPIp@c@DMB_@G]WUQE]Bq@XYL_@CaCUqAg@KSII[IQ@OFGFw@?q@Ge@SmBeAkIyAuDu@wAYuAOiCc@aCHsA@sCe@_HkAoHqAyAWs@Eo@C{GDcABmCC{@Cc@DeA?qHI_HIiD@g@DaB^{B^wAHiFJ}KVmGLkELs@JiA^{@\\IDJJhCfCj@h@RQr@u@" },
    {latlng: [-0.216652, -78.505795],
     date: 'March 3, 2019',
     title: 'Guest Post: We\'ll Always Have Quito',
     location: 'Quito, Pichincha, Ecuador',
     url: 'https://www.schemebasedadventure.com/2019/03/03/guest-post-well-always-have-quito/',
     corner1: [-0.240297, -78.531921],
     corner2: [-0.180808, -78.466502],
     line: '' },
    {latlng: [-0.802093, -78.921375],
     date: 'March 4, 2019',
     title: 'Three Days in Chugchil&aacute;n',
     location: 'Chugchil&aacute;n, Cotopaxi, Ecuador',
     url: 'https://www.schemebasedadventure.com/2019/03/04/chugchilan/',
     corner1: [-0.961115, -78.594512],
     corner2: [-0.658243, -78.960385],
     line: "`ii@fdd~MeGbCiCeO|J~Dx]rVxTwI|YRjEsE|MkLzDoBkKkV}Ve]sCkWiBgK`KuQhc@uG|OvIaCpIeVdFwFlSvHtEpJuN~ImD|^n_@tE~[lXzH~XfMfSrA|]oFtVlNrJpJjWdAl^vOxe@~a@fe@~Rbi@dDdxBtN~v@gHbb@wIvbA~Gfb@nNni@IvQhAzKfMxVfw@ln@we@dhBnTr\\rKzh@fN|GzO~TxLzH|OtSbNfoApS`j@tJty@~F~u@lObr@pYpv@vb@ln@PpaB|RvyA`SjqCta@pmCnk@x_Cdd@ll@lUp_@vd@l[t`@re@wHrE{QpMKnNxDdeA{E~m@uAnRmZ`\\oDbv@pEt`BuJzeB{VhNmElAaPxJmPjq@nQtPmWjHiDvfCtq@|qBbkAfk@j]bv@vQtVbSj_@`L`MtA~CnDfQQ|Sv^dNrHjOnH~Jr`@vCpf@l@jw@k@hU`Etn@rExVqHlRaOtc@X`YgIvVZhOkHjS{H`j@pN|WqKj[iSvVMfBoN`y@Ypu@~F~FlJvJ~GzKqAfW`Et`@sXjf@az@ntAoWiAoc@}JqQ\\_BzDqDwEaKVxGlG`GdP}ArJiIvPqB_Gmg@vNyQt@mL_F{FbCc@nDiFpCeAzGhEzHgRzD|EjLkRmB{D}BxF`IhJxLfP|FhDlSsFlDzAxUtBxUmDpe@sRxd@eB|NuCeG}@zFuBhKoBrCb@{YgOrWp@`NuBpBuAqYdA{EiCpFiDvW}ErUaN`SwM`_@gGv[iHbUsJvJqRfc@_IuDeM`EcLk@wFpGrWra@u^|Z}Eba@~DdJfJv@fLnS`@pM~KbDlAbQoGdN{CrH`EjDzQQhIaKpOvIfHxRjFdKmPcMqI{FxC`E}HlDhFhA_SdAoP`E}D`HdFnF~S{@tNzGfG~ScBdQt@xChIkChTaDrNkI_G|FrAzHpIzRxVqBxEtJnPyDlIVYwGhAyMfP}@tChE`^hYjIaB|QpLvHjLl@jPf@bF|CgE~GwLxF]{@rGqJ|KtPtR_@dGbIzDp@fDdCyGtAsWzGqCjEiTzIjAxAfM~GjN}@vG|E}Bc@`H|DtHjEkJjEyXn[rNtIgApBpJxDjLsCvH~EApIqClAiBe@oI`D}D~Eo@eF~GnHbQzG`QcCvJvGdHeIlM{@vFpHaBtMsAbDfNnDhCaAiF~FgIfKo@`@_LIuO~OjIDnJhDdJnFnKtF{MdBqK`J_EzGzDlJeDvKhClNo@dZvMvFTt@_G|K{@CtOhJ`@jTm@pUJ|OnLjEvG|GTpClTnA~RUzE|HyEtCwF" },
    {latlng: [-0.867114, -78.915954],
     date: 'March 5, 2019',
     title: 'Hiking Quilotoa!',
     location: 'Quilotoa, Cotopaxi, Ecuador',
     url: 'https://www.schemebasedadventure.com/2019/03/05/hiking-quilotoa/',
     corner1: [-0.797336, -78.930005],
     corner2: [-0.874365, -78.886891],
     line: "fs{Cvlu`NrATr@Pz@FhAB\\JPTD^C\\m@z@GXBVLZPRPXBVIfA?ZDTd@v@`@rA\\`Af@Vb@~@PTVFtAZbAj@ZFVGbBk@ZCTDNNDR@fAE~@c@tAShBk@xCGR]^Sf@?NFFNBd@Mb@W`@]p@q@`BmAf@OX?N@JNFb@LbAR`@Ld@@^GTm@\\MTIf@IZ[\\Uh@UfAAb@FVTXLV?RMTWXe@rAYv@CjADx@Lh@jAdCh@~BZz@\\b@nA`AxAp@j@`@j@Nf@DnA\\NV?f@KVu@l@Yx@EbADv@Pn@Tn@r@lA@b@Uj@q@t@E\\L^PPXJl@A`Ag@xBgBz@c@h@Qt@Ub@WVa@Li@B}@F]NOXAhBHb@MXWJ]BiAHmAZ[h@WN]@aBNOT@`@PjARlAClAPdA`@z@d@bAr@n@|@r@rBd@jBj@zCl@nATdAPfF?~@CX_@dAYpBCx@@f@L`@VJj@?VKn@cAdBgCx@s@Be@EgAJ{@b@aBAqAD_@JUt@_Ar@qAXOX@p@HHJBNAPSv@U`ACd@Bl@Tl@f@j@z@v@|AdBP`@?\\IVIr@J`@hAxBTX\\Nd@HTJLTDRb@vD^|AH`AB\\HVPJ\\Cl@Y`@Eb@LxBbBXFd@KLU@a@Ma@EcAC_AG_@Se@o@eBIUBYJ_@B_@YwA@c@J]nBaBb@C^LdB|@rDv@d@Td@l@f@`@dAd@~Cv@rDE`@ERMVk@Ae@u@aDa@eAmAcBM]EyAJm@NIPEVBXNfBdBb@Xd@Vj@Nt@Td@VtCbDhApAr@f@dIvF`@Nv@D|CLf@Hd@RpCtCPZL^ZtBH\\RRh@P\\ERIjJeCdC]|A{@^?ZHPTZ|@Vl@VZvBlAvAdB@ZETw@lAK\\BVJTPL`@@ZGdEs@d@Bd@Nn@\\b@NV?h@O`@g@|AwFR_@f@I`@?jBl@^FX?\\MjB{@d@Mh@@pAB^GXKTSN_@jAcIFi@C_@_@gAAUBYPWVMlAIp@C`@GfDiALQJYD]EYIUQW{Bo@qB]c@WoDiCi@i@Sg@Ia@BaB?m@Ou@{AcCmAcBOe@MgBBc@FYNYTYfE{CbLyJ`@_@JUFa@@c@?oBF}A@cCBWX]h@@p@d@l@|@f@XtJ|C`I~C`Ah@vBtBx@p@l@Hb@Q^e@`BuEb@o@n@c@p@GxDMfAW`Bs@dDu@x@[j@e@X_ATsBb@cDdEuHtEkGt@q@vG}FdGuAjK_Fb@_@Ru@Au@Ro@~AaBlAqFDMLWb@k@j@c@zAaAzAcAb@k@Ts@Jw@Fw@B]qIcMMKWWUYi@w@UYYUGCUEyBV_ARQF" },
    {latlng: [-2.893358, -79.007219],
     date: 'March 6, 2019',
     title: 'One Night in Cuenca',
     location: 'Cuenca, Azuay, Ecuador',
     url: 'https://www.schemebasedadventure.com/2019/03/06/one-night-in-cuenca/',
     corner1: [-2.889450, -79.012127],
     corner2: [-2.910408, -78.992356],
     line: "pjhD|gt`Nv[jDpgBc@liB{d@hvEum@||@KaBeRzy@c@tZuGt[{J~[mj@|Rk^uz@q]oj@fK|Fu`@gf@cSYwy@da@_b@{l@uQiWyk@qaApRs{@asAc_@mo@qf@G__@Jk`@qlAkt@sUjAwdBy_@i|@aZuYhb@iKnJwFdJgx@l`AodBoWgnBiPebAtbAoYza@c@iOeVxtAos@zwA{Blg@n@ul@yz@uj@qfEeOmk@`j@mR~eEkbB|kBorBliAqwAfjEuh@tlEiX~`Dq`@fgE}Sr~FeWz}Edy@n`BopAtc@s]~h@zZnq@v`@xLpnAzi@ka@tiDljBfaBe`@Ezd@pdAxpBff@xg@`zBfVl`Bz[rp@{CbyBdm@ncB}a@t}AdJjyCvr@bLps@nmAhWzz@jj@nxElzCjpBba@xyBxjAbxB~aBzyAy_@hu@iv@~eD{tAxM}|@hUbQjxBep@bt@m}@`cAo@h{@yV`i@b}AvG`w@yNtRfIh_@yXdmExa@xgA`XvGzmBtP~`B`pAh~CqZdyEkq@faDcpAzhAyv@`wClF|sDkN~nDyy@xoAurAnfBrVxoCaVxQu]ib@eS|PiNrnEd_AxjC|lAbjCfO|yIniBxpCay@td@fg@zgClm@lkCz|@`kAhnBcIjwBb\\pi@bw@qGfdBzjAvo@tk@jU~k@~Ajd@daAqViSle@z\\qDiPlc@`rApLbpAbfAmYsz@hl@vg@nWeO~MgfAmFceAtQ{s@jJcgC~~@zlExp@tpCpIph@tc@zWqV~KjB`z@jz@fzAt_@nEuNzf@zh@~c@dF~g@jTh|@z|@vWbr@auAlaAmI~\\nQol@rl@bGzm@v}@lOthA{BxBzm@~nAxRpj@wDlbAjf@~KnYk]~y@}Qjr@~i@`Zd`BRzr@{_@dArXrYdUlYoW`j@lEnKhy@gj@zc@bI~XxqA~dBn\\hJbRih@f{Adx@lWck@pC}u@~vBhz@twAlp@vz@idAjm@|Z`Uan@es@yq@}OeuBdXcxAhZwe@zr@xGtj@euAwGo`@zd@_g@nrApKni@iGr`@ee@eChiAptBvc@`d@i_@a]cMvb@{e@fYdUtfA_a@|Dym@t[~Mr[|Urn@iOhqBkWdrAjKllCcIdd@p{@tx@a_Afg@hLhTem@rH_^q_@Aln@gt@vrCuV`f@_NcK`[bXdWn{@i_@d~@mb@oLen@de@}cC`nB}h@p`CreAveBzMpy@ngArnB|`@bf@fXfaBsn@n{@|\\tq@|qC~nApgDnbCrbBtY|vAew@dgAxFftAz`AjsB" }
    // {latlng: [],
    //  date: '',
    //  title: '',
    //  location: '',
    //  url: '',
    //  corner1: [],
    //  corner2: [],
    //  line: '' }
];

// HOW TO OBTAIN A POLYLINE
// Visit the following Google Maps Directions API endpoint (typical location strings given; default mode is driving):
// https://maps.googleapis.com/maps/api/directions/json?origin=37.840455,-122.257520&destination=Universal+Studios+Hollywood&key=API_KEY
// Don't forget to replace API_KEY with your API key (get one here https://developers.google.com/maps/documentation/directions/start#get-a-key)
// Near the bottom, under "overview_polyline", copy the value associated with key "points"
// Copy the whole string, including enclosing "", and leave any \ characters escaped with a second \
// Replace the boilerplate '' with the copied string